### PR TITLE
Bubble sort and selection sort in java with minimum complexity

### PR DESCRIPTION
**Pull request by Hussain6**
I have pulled the bubble and selection sort algorithms can you just merge the repo and assign the hacktoberfest labels. Thanks

### CODE REVIEW

**Review by ianshulx — APPROVED** [review]
Thanks, @Hussain6 for your contribution, Please dont forget to star this repo.

**Comment by Hussain6** [comment]
Welcome @ianshulx i have star the repo. If you are having any other issues you can mention them too.

**Comment by ianshulx** [comment]
Definitely @Hussain6, I'll ask you If there"ll be any issue, thanks for your ask.

**Comment by Hussain6** [comment]
Welcome

**Pull request merged**
